<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hello hkit, lets complete the test form</name>
   <tag></tag>
   <elementGuidId>48d13cba-f411-416e-97c0-90648c6afae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#greetings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='greetings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ad559cf0-7d11-4fcb-b2b5-8ce84c94d953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greetings</value>
      <webElementGuid>56962ed4-ff69-4306-a28b-ef5272392c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello hkit, let's complete the test form:</value>
      <webElementGuid>c09d487c-8a84-45de-abd8-30bb82cab1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greetings&quot;)</value>
      <webElementGuid>d342a287-c46f-4b0e-83f9-023321a19be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='greetings']</value>
      <webElementGuid>6c9614be-6f93-4067-a8f1-be9001a3fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageProfile']/p</value>
      <webElementGuid>21b049b1-8ef2-445e-8594-2208025a2db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestProject Example page'])[2]/following::p[1]</value>
      <webElementGuid>42b5a75d-efa9-437e-8d3e-2025debd31e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>4b93ac2e-7b2e-434f-ab53-1beed09b8392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::p[1]</value>
      <webElementGuid>cfc70595-9f3f-4dca-80d9-5ee38c58b814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>ca656f4f-ee5a-46be-ba80-97bcaafbe3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>0671cf05-e4fc-47d2-8a5b-9119690bd026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'greetings' and (text() = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;) or . = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;))]</value>
      <webElementGuid>a0a155da-d6b6-489a-a897-b44a0b38c6fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
